const { default: makeWASocket, BufferJSON, WA_DEFAULT_EPHEMERAL, generateWAMessageFromContent, downloadContentFromMessage, downloadHistory, proto, getContentType, generateWAMessageContent, prepareWAMessageMedia } = require('@whiskeysockets/baileys');
const axios = require('axios');
const fs = require('fs');
const { translateToEn } = require('../lib/translate');
const { t } = require('../lib/language');

module.exports = async (sock, chatId, msg, args, commands, userLang) => {
    try {
        const text = Array.isArray(args) ? args.join(' ') : args;
        if (!text || text.trim().length === 0) return sock.sendMessage(chatId, { text: t('ai.provide_prompt', {}, userLang) }, { quoted: msg });


        // Translate Arabic to English for better AI results
        const promptText = await translateToEn(text);

        const prompt = encodeURIComponent(promptText);
        const url = `https://image.pollinations.ai/prompt/${prompt}?width=1024&height=1024&seed=${Math.floor(Math.random() * 1000000)}&nologo=true`;

        await sock.sendMessage(chatId, { text: t('ai.wait', {}, userLang) }, { quoted: msg });

        const response = await axios.get(url, { responseType: 'arraybuffer' });
        const buffer = Buffer.from(response.data, 'binary');

        await sock.sendMessage(chatId, {
            image: buffer,
            caption: `🎨 *Art Generated by Hamza Amirni* ⚔️\n\n📝 *Prompt:* ${text}\n👤 *By:* Hamza Amirni`,
            headerType: 4
        }, { quoted: msg });

    } catch (err) {
        console.error(err);
        await sock.sendMessage(chatId, { text: t('ai.error', {}, userLang) }, { quoted: msg });
    }
};
