const entries = [
    [1, ['الفاتحة', 'الفاتحه', 'فاتحة', 'alfatiha', 'al-fatiha', 'fatiha', 'al-fatihah']],
    [2, ['البقرة', 'بقرة', 'baqarah', 'al-baqarah']],
    [3, ['آل عمران', 'ال عمران', 'عمران', 'ali imran', 'aal imran', 'ali-imran']],
    [4, ['النساء', 'نساء', 'an-nisa', 'nisa']],
    [5, ['المائدة', 'مايدة', 'm5a', 'al-maidah', 'maidah']],
    [6, ['الأنعام', 'الانعام', 'انعام', 'al-anam', 'al-anaam', 'anam']],
    [7, ['الأعراف', 'الاعراف', 'اعراف', 'al-araf', 'al-araf', 'araf']],
    [8, ['الأنفال', 'الانفال', 'انفال', 'al-anfal', 'anfal']],
    [9, ['التوبة', 'توبة', 'al-tawbah', 'tawbah', 'taubah']],
    [10, ['يونس', 'yunus', 'younus']],
    [11, ['هود', 'hud']],
    [12, ['يوسف', 'yusuf', 'youssef']],
    [13, ['الرعد', 'رعد', 'al-rad', 'raad', 'rad']],
    [14, ['ابراهيم', 'إبراهيم', 'ibrahim']],
    [15, ['الحجر', 'hijr', 'al-hijr']],
    [16, ['النحل', 'نحل', 'an-nahl', 'nahl']],
    [17, ['الإسراء', 'الاسراء', 'اسراء', 'isra', 'al-isra', 'bani israel']],
    [18, ['الكهف', 'كهف', 'al-kahf', 'kahf']],
    [19, ['مريم', 'maryam']],
    [20, ['طه', 'ta-ha', 'taha']],
    [21, ['الأنبياء', 'الانبياء', 'انبياء', 'al-anbiya', 'anbiya']],
    [22, ['الحج', 'hajj', 'al-hajj']],
    [23, ['المؤمنون', 'المؤمنين', 'al-muminun', 'muminun', 'mukminun']],
    [24, ['النور', 'نور', 'an-nur', 'nur']],
    [25, ['الفرقان', 'furqan', 'al-furqan']],
    [26, ['الشعراء', 'شعراء', 'ash-shuara', 'shuara']],
    [27, ['النمل', 'نمل', 'an-naml', 'naml']],
    [28, ['القصص', 'قصص', 'al-qasas', 'qasas']],
    [29, ['العنكبوت', 'عنكبوت', 'al-ankabut', 'ankabut']],
    [30, ['الروم', 'روم', 'ar-rum', 'rum']],
    [31, ['لقمان', 'luqman']],
    [32, ['السجدة', 'السجده', 'sajdah', 'as-sajdah']],
    [33, ['الأحزاب', 'الاحزاب', 'احزاب', 'ahzab', 'al-ahzab']],
    [34, ['سبإ', 'سبأ', 'saba']],
    [35, ['فاطر', 'fatir']],
    [36, ['يس', 'يـس', 'yas', 'yaseen', 'ya-sin', 'ya-sin', 'yasin', 'yaasin']],
    [37, ['الصافات', 'الصافات', 'صافات', 'as-saffat', 'saffat']],
    [38, ['ص', 'sad']],
    [39, ['الزمر', 'زمر', 'az-zumar', 'zumar']],
    [40, ['غافر', 'ghafir', 'mumin']],
    [41, ['فصلت', 'fussilat', 'fusilat']],
    [42, ['الشورى', 'شورى', 'ash-shura', 'shura']],
    [43, ['الزخرف', 'زخرف', 'az-zukhruf', 'zukhruf']],
    [44, ['الدخان', 'دخان', 'ad-dukhan', 'dukhan']],
    [45, ['الجاثية', 'جاثية', 'al-jathiyah', 'jathiyah']],
    [46, ['الأحقاف', 'الاحقاف', 'احقاف', 'al-ahqaf', 'ahqaf']],
    [47, ['محمد', 'muhammad']],
    [48, ['الفتح', 'فتح', 'al-fath', 'fath']],
    [49, ['الحجرات', 'حجرات', 'al-hujurat', 'hujurat']],
    [50, ['ق', 'qaf']],
    [51, ['الذاريات', 'ذاريات', 'adh-dhariyat', 'dhariyat']],
    [52, ['الطور', 'طور', 'at-tur', 'tur']],
    [53, ['النجم', 'نجم', 'an-najm', 'najm']],
    [54, ['القمر', 'قمر', 'al-qamar', 'qamar']],
    [55, ['الرحمن', 'رحمن', 'ar-rahman', 'rahman']],
    [56, ['الواقعة', 'واقعة', 'al-waqia', 'waqia', 'waqiah']],
    [57, ['الحديد', 'حديد', 'al-hadid', 'hadid']],
    [58, ['المجادلة', 'مجادلة', 'al-mujadila', 'mujadila']],
    [59, ['الحشر', 'حشر', 'al-hashr', 'hashr']],
    [60, ['الممتحنة', 'ممتحنة', 'al-mumtahina', 'mumtahina']],
    [61, ['الصف', 'صف', 'as-saff', 'saff']],
    [62, ['الجمعة', 'جمعه', 'jumuah', 'al-jumuah']],
    [63, ['المنافقون', 'منافقون', 'al-munafiqun', 'munafiqun']],
    [64, ['التغابن', 'taghabun', 'at-taghabun']],
    [65, ['الطلاق', 'طلاق', 'at-talaq', 'talaq']],
    [66, ['التحريم', 'تحريم', 'at-tahrim', 'tahrim']],
    [67, ['الملك', 'ملك', 'al-mulk', 'mulk']],
    [68, ['القلم', 'قلم', 'al-qalam', 'qalam']],
    [69, ['الحاقة', 'الحاقه', 'haqqah', 'al-haqqah']],
    [70, ['المعارج', 'معارج', 'al-maarij', 'maarij']],
    [71, ['نوح', 'nuh', 'nooh']],
    [72, ['الجن', 'جن', 'al-jinn', 'jinn']],
    [73, ['المزمل', 'مزمل', 'al-muzzammil', 'muzzammil']],
    [74, ['المدثر', 'مدثر', 'al-muddathir', 'muddathir']],
    [75, ['القيامة', 'قيامه', 'قيامة', 'al-qiyamah', 'qiyamah']],
    [76, ['الإنسان', 'الانسان', 'انسان', 'al-insan', 'insan']],
    [77, ['المرسلات', 'مرسلات', 'al-mursalat', 'mursalat']],
    [78, ['النبإ', 'النبأ', 'naba', 'an-naba']],
    [79, ['النازعات', 'نازعات', 'an-naziat', 'naziat']],
    [80, ['عبس', 'abasa', 'abasa']],
    [81, ['التكوير', 'تكوير', 'at-takwir', 'takwir']],
    [82, ['الانفطار', 'انفطار', 'al-infitar', 'infitar']],
    [83, ['المطففين', 'مطففين', 'al-mutaffifin', 'mutaffifin']],
    [84, ['الانشقاق', 'انشقاق', 'al-inshiqaq', 'inshiqaq']],
    [85, ['البروج', 'بروج', 'al-buruj', 'buruj']],
    [86, ['الطارق', 'طارق', 'at-tariq', 'tariq']],
    [87, ['الأعلى', 'الاعلى', 'اعلى', 'al-ala', 'ala']],
    [88, ['الغاشية', 'غاشية', 'al-ghashiyah', 'ghashiyah']],
    [89, ['الفجر', 'فجر', 'al-fajr', 'fajr']],
    [90, ['البلد', 'بلد', 'al-balad', 'balad']],
    [91, ['الشمس', 'شمس', 'ash-shams', 'shams']],
    [92, ['الليل', 'ليل', 'al-layl', 'layl']],
    [93, ['الضحى', 'ضحى', 'ad-duha', 'duha']],
    [94, ['الشرح', 'شرح', 'ash-sharh', 'sharh', 'al-inshirah', 'inshirah']],
    [95, ['التين', 'تين', 'at-tin', 'tin']],
    [96, ['العلق', 'علق', 'al-alaq', 'alaq']],
    [97, ['القدر', 'قدر', 'al-qadr', 'qadr']],
    [98, ['البينة', 'بينه', 'بينة', 'al-bayyinah', 'bayyinah']],
    [99, ['الزلزلة', 'زلزلة', 'az-zalzalah', 'zalzalah']],
    [100, ['العاديات', 'عاديات', 'al-adiyat', 'adiyat']],
    [101, ['القارعة', 'قارعه', 'قارعة', 'al-qariah', 'qariah']],
    [102, ['التكاثر', 'تكاثر', 'at-takathur', 'takathur']],
    [103, ['العصر', 'asr', 'al-asr']],
    [104, ['الهمزة', 'همزة', 'al-humazah', 'humazah']],
    [105, ['الفيل', 'فيل', 'al-fil', 'fil']],
    [106, ['قريش', 'quraysh', 'quraish']],
    [107, ['الماعون', 'ماعون', 'al-maun', 'maun', 'maaun']],
    [108, ['الكوثر', 'كوثر', 'al-kawthar', 'kawthar']],
    [109, ['الكافرون', 'كافرون', 'al-kafirun', 'kafirun']],
    [110, ['النصر', 'نصر', 'an-nasr', 'nasr']],
    [111, ['المسد', 'مسد', 'al-masad', 'masad', 'al-lahab', 'lahab']],
    [112, ['الإخلاص', 'الاخلاص', 'اخلاص', 'al-ikhlas', 'ikhlas']],
    [113, ['الفلق', 'فلق', 'al-falaq', 'falaq']],
    [114, ['الناس', 'ناس', 'an-nas', 'nas']]
];

const SURAH_NAME_MAP = new Map();
for (const [num, names] of entries) {
    for (const n of names) {
        SURAH_NAME_MAP.set(n.toLowerCase(), num);
    }
}

function getSurahNumber(input) {
    if (!input) return null;
    let num = parseInt(input, 10);
    if (!isNaN(num)) return num;
    return SURAH_NAME_MAP.get(input.toLowerCase()) || null;
}

module.exports = {
    SURAH_NAME_MAP,
    getSurahNumber
};
